export const initialLayout = {
  modelName: '{%modelName%}',
  listAction: [
    {
      name: 'edit',
      title: 'Edit',
      type: 'primary',
      call: 'modal',
      uri: '/api/{%modelName%}/:id',
      method: 'get',
    },
    {
      name: 'page-edit',
      title: 'Page Edit',
      type: 'default',
      call: 'page',
      uri: '/api/{%modelName%}/:id',
      method: 'get',
    },
    {
      name: 'delete',
      title: 'Delete',
      type: 'default',
      call: 'delete',
      uri: '/api/{%modelName%}/delete',
      method: 'post',
    },
  ],
  addAction: [
    {
      name: 'reset',
      title: 'Reset',
      type: 'dashed',
      call: 'reset',
      method: 'get',
    },
    {
      name: 'cancel',
      title: 'Cancel',
      type: 'default',
      call: 'cancel',
      method: 'get',
    },
    {
      name: 'submit',
      title: 'Submit',
      type: 'primary',
      call: 'submit',
      uri: '/api/{%modelName%}',
      method: 'post',
    },
  ],
  editAction: [
    {
      name: 'reset',
      title: 'Reset',
      type: 'dashed',
      call: 'reset',
      method: 'get',
    },
    {
      name: 'cancel',
      title: 'Cancel',
      type: 'default',
      call: 'cancel',
      method: 'get',
    },
    {
      name: 'submit',
      title: 'Submit',
      type: 'primary',
      call: 'submit',
      uri: '/api/{%modelName%}/:id',
      method: 'put',
    },
  ],
  tableToolbar: [
    {
      name: 'add',
      title: 'Add',
      type: 'primary',
      call: 'modal',
      uri: '/api/{%modelName%}/add',
      method: 'get',
    },
    {
      name: 'page-add',
      title: 'Page Add',
      type: 'default',
      call: 'page',
      uri: '/api/{%modelName%}/add',
      method: 'get',
    },
    {
      name: 'reload',
      title: 'Reload',
      type: 'default',
      call: 'reload',
      method: 'get',
    },
  ],
  batchToolbar: [
    {
      name: 'delete',
      title: 'Delete',
      type: 'danger',
      call: 'delete',
      uri: '/api/{%modelName%}/delete',
      method: 'post',
    },
    {
      name: 'disabled',
      title: 'Disabled',
      type: 'default',
      call: 'disabled',
      uri: '/api/{%modelName%}/disable',
      method: 'post',
    },
  ],
  batchToolbarTrashed: [
    {
      name: 'delete-permanently',
      title: 'Delete Permanently',
      type: 'danger',
      call: 'deletePermanently',
      method: 'post',
      uri: '/api/{%modelName%}/delete',
    },
    {
      name: 'restore',
      title: 'Restore',
      type: 'default',
      call: 'restore',
      uri: '/api/{%modelName%}/restore',
      method: 'post',
    },
  ],
};
