export const initialLayout = {
  listAction: [
    {
      name: 'edit',
      title: 'Edit',
      type: 'primary',
      call: 'modal',
      uri: '/api/{%tableName%}/:id',
      method: 'get',
    },
    {
      name: 'page_edit',
      title: 'Page Edit',
      type: 'default',
      call: 'page',
      uri: '/api/{%tableName%}/:id',
      method: 'get',
    },
    {
      name: 'delete',
      title: 'Delete',
      type: 'default',
      call: 'delete',
      uri: '/api/{%tableName%}/delete',
      method: 'post',
    },
  ],
  addAction: [
    {
      name: 'reset',
      title: 'Reset',
      type: 'dashed',
      call: 'reset',
      method: 'get',
    },
    {
      name: 'cancel',
      title: 'Cancel',
      type: 'default',
      call: 'cancel',
      method: 'get',
    },
    {
      name: 'submit',
      title: 'Submit',
      type: 'primary',
      call: 'submit',
      uri: '/api/{%tableName%}',
      method: 'post',
    },
  ],
  editAction: [
    {
      name: 'cancel',
      title: 'Cancel',
      type: 'default',
      call: 'cancel',
      method: 'get',
    },
    {
      name: 'submit',
      title: 'Submit',
      type: 'primary',
      call: 'submit',
      uri: '/api/{%tableName%}/:id',
      method: 'put',
    },
  ],
  tableToolbar: [
    {
      name: 'add',
      title: 'Add',
      type: 'primary',
      call: 'modal',
      uri: '/api/{%tableName%}/add',
      method: 'get',
    },
    {
      name: 'page_add',
      title: 'Page Add',
      type: 'default',
      call: 'page',
      uri: '/api/{%tableName%}/add',
      method: 'get',
    },
  ],
  batchToolbar: [
    {
      name: 'delete',
      title: 'Delete',
      type: 'danger',
      call: 'delete',
      uri: '/api/{%tableName%}/delete',
      method: 'post',
    },
    {
      name: 'disable',
      title: 'Disable',
      type: 'default',
      call: 'disable',
      uri: '/api/{%tableName%}/disable',
      method: 'post',
    },
  ],
  batchToolbarTrashed: [
    {
      name: 'delete_permanently',
      title: 'Delete Permanently',
      type: 'danger',
      call: 'deletePermanently',
      method: 'post',
      uri: '/api/{%tableName%}/delete',
    },
    {
      name: 'restore',
      title: 'Restore',
      type: 'default',
      call: 'restore',
      uri: '/api/{%tableName%}/restore',
      method: 'post',
    },
  ],
};
